In [2]:
# ==========================================
# Import Libraries
# ==========================================

import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display full text in cells
pd.set_option("display.max_colwidth", None)

In [3]:
# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("../data/Reviews.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [4]:
# Display first five rows

df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than most.
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,"Product arrived labeled as Jumbo Salted Peanuts...the peanuts were actually small sized unsalted. Not sure if this was an error or if the vendor intended to represent the product as ""Jumbo""."
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all","This is a confection that has been around a few centuries. It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar. And it is a tiny mouthful of heaven. Not too chewy, and very flavorful. I highly recommend this yummy treat. If you are familiar with the story of C.S. Lewis' ""The Lion, The Witch, and The Wardrobe"" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch."
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient in Robitussin I believe I have found it. I got this in addition to the Root Beer Extract I ordered (which was good) and made some cherry soda. The flavor is very medicinal.
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,"Great taffy at a great price. There was a wide assortment of yummy taffy. Delivery was very quick. If your a taffy lover, this is a deal."

In [5]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 568454
Columns : 10

In [6]:
df.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  str
 2   UserId                  568454 non-null  str
 3   ProfileName             568428 non-null  str
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  str
 9   Text                    568454 non-null  str
dtypes: int64(5), str(5)
memory usage: 313.1 MB

In [8]:
df.describe()

,Id,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
count,568454.000000,568454.000000,568454.00000,568454.000000,5.684540e+05
mean,284227.500000,1.743817,2.22881,4.183199,1.296257e+09
std,164098.679298,7.636513,8.28974,1.310436,4.804331e+07
min,1.000000,0.000000,0.00000,1.000000,9.393408e+08
25%,142114.250000,0.000000,0.00000,4.000000,1.271290e+09
50%,284227.500000,0.000000,1.00000,5.000000,1.311120e+09
75%,426340.750000,2.000000,2.00000,5.000000,1.332720e+09
max,568454.000000,866.000000,923.00000,5.000000,1.351210e+09

In [9]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [10]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [11]:
df["Score"].value_counts().sort_index()

Score
1     52268
2     29769
3     42640
4     80655
5    363122
Name: count, dtype: int64

In [12]:
df[["Score", "Summary", "Text"]].sample(10, random_state=42)

,Score,Summary,Text
165256,5,Crunchy & Good Gluten-Free Sandwich Cookies!,"Having tried a couple of other brands of gluten-free sandwich cookies, these are the best of the bunch. They're crunchy and true to the texture of the other ""real"" cookies that aren't gluten-free. Some might think that the filling makes them a bit too sweet, but for me that just means I've satisfied my sweet tooth sooner! The chocolate version from Glutino is just as good and has a true ""chocolatey"" taste - something that isn't there with the other gluten-free brands out there."
231465,5,great kitty treats,"My cat loves these treats. If ever I can't find her in the house, I just pop the top and she bolts out of wherever she was hiding to come get a treat. She doesn't like crunchy treats much, so these are perfect for her. I've given her all three flavors and she seems to like them all equally. They do tend to dry out by the time I near the end of the bottle, however. The flip-top lid is very handy. Very nice, inexpensive kitty treats. I have yet to meet a cat that doesn't just love these!"
427827,3,COFFEE TASTE,A little less than I expected. It tends to have a muddy taste - not what I expected since they said it was the favorite of the company.
433954,2,So the Mini-Wheats were too big?,"First there was Frosted Mini-Wheats, in original size, then there was Frosted Mini-Wheats Bite Size. Well, if for some reason those were too much of a mouthful, we now have Frosted Mini-Wheats Little Bits. Yes, these are about half the size of the Bite Size versions. This particular one is ""Cinnamon Roll"".<br /><br />There is nothing new to the table here with the exception of size, which I is unnecessary. Personally, I like original flavor and size the best. But the Bite Size edition were accommodating. These come off as a desperate attempt to give attention to a brand that needs some sort of life put back into it and all they came up with was making them smaller and having a new flavor, which is actually too sweet for me.<br /><br />A serving size is approximately 47 biscuits. Thats 1 gram of polyunsaturated fat, 46 grams of carbohydrates, 6g fiber, 12g of sugar, 5g of protein and 200mg of potassium. Generally they look good but I guess those that are watching their carb intake might want to be careful.<br /><br />These probably fit on a spoon better than its predecessors in a bowl of milk, but I like the other kinds cause they snack better without the milk. But here, these small ones are easily to snack more than you should.<br /><br />I am grading this product 2 stars for 3 reasons 1) I dont think making them smaller has any reason for existing outside of Kellogs filling the shelves with more versions of something that was fine to begin with. 2) This flavor, Cinnamon Roll, is sweet and has a synthetic taste to it. 3) On the plus side, I like Mini-Wheats in general, so it saved it from being one star."
70260,5,Great Taste . . .,"and I want to congratulate the graphic artist for putting the entire product name on such a small box. The ad men must have really thought long and hard.<br /><br />But seriously, I love the product. The taste was refreshing and I thought that the taste was pleasing with no aftertaste. Not too sweet and Goldilocks would have stopped right there if there was a choice of 3. Easy to use as you just pour the contents into a 16 oz bottle of water and shake. Mixed well, no granulation, you really couldn't ask for anything more and Lipton like a good drug dealer knows what they are doing, give me a taste for free and have me for life. 5 stars."
49866,4,Lifesavers - Pineapple flavor,"Please add more Pineapple flavor to your packages of lifesavers, in fact, can you sell pineapple flavor by itself?"
551047,5,The Best Tea!,I absolutely love Yorkshire tea and am so glad it is now available on Amazon! A cup of this full-bodied black tea with milk in the morning is how I start each day and just love it!
18983,5,Lady Grey a hit!,I have such a hard time finding loose tea locally. Being able to order my favorite Lady Grey tea on Amazon is convenient and timesaving. The tea comes in a six-pack of tins that are just the right size to insure continued freshness. Speedy shipping too!
138968,4,Pretty good rice noodles,"Previously, I've attempted a recipe with white rice noodles and overcooked them, which made them soggy. So I was determined not to overcook these brown rice noodles. I tried making two dishes. The first was a miso soup with brown rice noodles, which was really just broth with miso and green onions and the noodles added when it was hot. The noodles softened and puffed up, but I think I should of softened them in water and maybe rinsed them first. The broth ended up being a little starchy from the noodles, but it was pretty good.<br /><br />The noodles by themselves don't really have any flavor, they just take on the flavor of whatever dish they are in. So the rice noodles in miso probably wasn't the best idea because the mild miso flavor didn't really give the noodles much flavor. I also tried stir frying the noodles which was much better. I just soaked the noodles in hot water, for about a minute, and then drained them. They came out clear and kind of crunchy. Then I stir fried them with garlic, onion, salt, and coconut oil. I also added some vinegar and nama shoyu for flavor. These noodles came out crunchy and spicy and actually were pretty good.<br /><br />The nice thing about these noodles is they only need about a minute in warm water and then they can be fried or added to soups or other dishes, so they are fairly versatile. They are also gluten free and the brown rice noodles seem more firm than the white rice noodles. As another reviewer posted it does look like these noodles are made in Singapore."
36352,5,Simply the best,"I make pancakes or waffles every Saturday morning with my kids, and there simply is no comparison between this product and any other baking powder I have come across. Even the more expensive brands from Trader Joe's or Whole Foods pale in comparison. Batter comes out light and fluffy every time, and my kids love them. I have also been known to eat a pancake or two. Get the pack of 6 and store up."

In [13]:
(df["Text"].str.strip() == "").sum()

np.int64(0)